#Global
PARENT_DIR = "PARENT_DIR"

#Logging
LOG_FILE = "LOG_FILE"
SAVE_DIR = "SAVE_DIR"
TENSORBOARD_LOG_DIR = "TENSORBOARD_LOG_DIR"

#Preprocessing Dataset
DATASET_PATH = "DATASET_PATH"

#DeepSense Parameters
##Dataset Parameters
BATCH_SIZE = "BATCH_SIZE"
HISTORY_LENGTH = "HISTORY_LENGTH"
HORIZON = "HORIZON"
MEMORY_SIZE = "MEMORY_SIZE"
NUM_ACTIONS = "NUM_ACTIONS"
NUM_CHANNELS = "NUM_CHANNELS"
SPLIT_SIZE = "SPLIT_SIZE"
WINDOW_SIZE = "WINDOW_SIZE"

##Dropout Layer Parameters
CONV_KEEP_PROB = "CONV_KEEP_PROB"
DENSE_KEEP_PROB = "DENSE_KEEP_PROB"
GRU_KEEP_PROB = "GRU_KEEP_PROB"

## Convolution Layer Parameters
FILTER_SIZES = "FILTER_SIZES"
KERNEL_SIZES = "KERNEL_SIZES"
PADDING = "PADDING"
SAME = "SAME"
VALID = "VALID"

## GRU Parameters
GRU_CELL_SIZE = "GRU_CELL_SIZE"
GRU_NUM_CELLS = "GRU_NUM_CELLS"

##FullyConnected Layer Parameters
DENSE_LAYER_SIZES = "DENSE_LAYER_SIZES"

#configuration section names
CONVOLUTION = "convolution"
DATASET = "dataset"
DENSE = "dense"
DROPOUT = "dropout"
GLOBAL = "global"
GRU = "gru"
LOGGING = "logging"
PREPROCESSING = "preprocessing"