#strings
BATCH_NORM_ = "batch_norm_{}"
CONV_ = "conv_{}"
DEEPSENSE = "DeepSense"
DENSE_  = "dense_"
DROPOUT_CONV_ = "dropout_conv_{}"
DROPOUT_DENSE_ = "dropout_dense_{}"
GRU_CELL_ = "gru_cell_{}"
INFERENCE = "inference"
Q_VALUES = "q_values"
