#strings
ACTIONS = "actions"
DEEP_TRADING_AGENT = "deep_trading_agent"
POSTSTATES = "poststates"
PRESTATES = "prestates"
REPLAY_MEMORY = "replay_memory"
REWARDS = "rewards"
SCREENS = "screens"
STEP = "step"
STEPS = "steps"
STEP_INPUT = "step_input"
Q_NETWORK = "q_network"
TERMINALS = "terminals"
T_Q_NETWORK = "t_q_network"

BATCH_NORM_ = "batch_norm_{}"
CONV_LAYERS = "conv_layers"
CONV_ = "conv_{}"
CONV_LAYERS_ = "conv_layer_{}"
DEEPSENSE = "DeepSense"
DENSE_  = "dense_{}"
DENSE_LAYER_ = "dense_layer_{}"
DROPOUT_CONV_ = "dropout_conv_{}"
DROPOUT_DENSE_ = "dropout_dense_{}"
DYNAMIC_UNROLLING = "dynamic_unrolling"
FULLY_CONNECTED = "fully_connected"
GRU_CELL_ = "gru_cell_{}"
INFERENCE = "inference"
INPUT = "input"
INPUT_PARAMS = "input_params"
Q_VALUES = "q_values"
WEIGHTS_LOADER = "weights_loader"

#Log Messages
MODEL_WEIGHTS_NOT_LOADED = "MODEL_WEIGHTS_NOT_LOADED"
PRE_TRAINED_MODEL_NOT_LOADED = "PRE_TRAINED_MODEL_NOT_LOADED"
REPLAY_MEMORY_ZERO = "REPLAY_MEMORY_ZERO"
REPLAY_MEMORY_INSUFFICIENT = "REPLAY_MEMORY_INSUFFICIENT"